# Generated by Django 4.2.3 on 2023-11-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0002_alter_regmodel_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regmodel',
            name='img',
            field=models.FileField(upload_to='bank_app/static'),
        ),
    ]
