# Generated by Django 4.2.3 on 2023-11-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0005_depositamount_withdrawamount'),
    ]

    operations = [
        migrations.CreateModel(
            name='mini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.IntegerField()),
            ],
        ),
    ]
