# Generated by Django 4.2.3 on 2023-11-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0007_newsfeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeed',
            name='content',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='newsfeed',
            name='topic',
            field=models.CharField(max_length=200),
        ),
    ]
