# Generated by Django 4.2.3 on 2023-11-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0008_alter_newsfeed_content_alter_newsfeed_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='savenew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=1000)),
                ('date', models.DateField()),
            ],
        ),
    ]
