# Generated by Django 4.2.3 on 2023-11-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0009_savenew'),
    ]

    operations = [
        migrations.AddField(
            model_name='savenew',
            name='newsid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
