# Generated by Django 4.2.3 on 2023-11-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0010_savenew_newsid'),
    ]

    operations = [
        migrations.AddField(
            model_name='savenew',
            name='uid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
